NumPy is a fundamental library for scientific computing. We will focus on arrays and vectorized operations through NumPy

In [2]:
import numpy as np

In [7]:
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [9]:
arr2 = np.array([1, 2, 3, 4, 5])
# 2-d Array
arr2.reshape(1, 5)

array([[1, 2, 3, 4, 5]])

In [14]:
# reshape to get 5 rows and 1 column
np.arange(0, 10, 2).reshape(5, 1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [16]:
# NnumPy inbuilt function example:
np.ones((3, 4))  # This gives 3 rows and 4 columns

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
# Identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Numpy Operations commonly used:
arr.shape <br/>
arr.ndim (To calculate number of dimensions) <br/>
arr.size (No. of elements) <br/>
arr.dtype (Data type) <br/>
arr.itemsize (data in bytes) <br/>

In [20]:
### Universal Function
arr = np.array([2, 3, 4, 5, 6])

# Square root calculation
print(np.sqrt(arr))

print(np.exp(arr))

print(np.sin(arr))

print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [21]:
### Array slicing & Indexing
arr = np.array([ [1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12] ])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [23]:
print(arr[0][0])

1


In [24]:
arr[1:, 2:]

array([[ 7,  8],
       [11, 12]])

In [25]:
arr[1:, 1:3]

array([[ 6,  7],
       [10, 11]])

In [26]:
### Logical operation
data = np.array( [1, 2, 3, 4, 5, 6, 7, 8] )

data[data > 5]

array([6, 7, 8])